"""empty message

Revision ID: 28b32156a6fb
Revises: 6b6c0b06e57c
Create Date: 2018-07-13 15:01:33.237660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28b32156a6fb'
down_revision = '6b6c0b06e57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_api_token_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_api_token_key', 'users', ['api_token'])
    # ### end Alembic commands ###
