"""empty message

Revision ID: 65c7a5c70753
Revises: 28b32156a6fb
Create Date: 2018-07-13 15:18:33.437225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65c7a5c70753'
down_revision = '28b32156a6fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'api_token',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['api_token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'api_token',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
