"""empty message

Revision ID: 6b6c0b06e57c
Revises: 943305588688
Create Date: 2018-07-13 14:49:13.041999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6c0b06e57c'
down_revision = '943305588688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweets', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tweets', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweets', type_='foreignkey')
    op.drop_column('tweets', 'user_id')
    # ### end Alembic commands ###
