"""empty message

Revision ID: 943305588688
Revises: 707eeca9417f
Create Date: 2018-07-12 16:09:03.300770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943305588688'
down_revision = '707eeca9417f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('api_token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_token'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
